//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace odec.CP.Server.Model.Personal.Store.Migrations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _201604252318515_BlobPersonalStoreInitial {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal _201604252318515_BlobPersonalStoreInitial() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("odec.CP.Server.Model.Personal.Store.Migrations.201604252318515_BlobPersonalStoreI" +
                            "nitial", typeof(_201604252318515_BlobPersonalStoreInitial).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAO092W7cypXvA8w/NPppJrhRS3Yc3BhSAllerhDLV5HsZN4Emk1JxO0mOyTbV8ogXzYP80nzC1PFtZZzaiGLSzuEAaNVy1nqLLWwzqn/+5//Pf3T03az+BYkaRhHZ8uTo+PlIoj8eB1GD2fLfXb/2x+Xf/rjv//b6bv19mnx16rdS9qO9IzSs+Vjlu1er1ap/xhsvfRoG/pJnMb32ZEfb1feOl69OD7+w+rkZBUQEEsCa7E4vdlHWbgN8j/Inxdx5Ae7bO9truJ1sEnLclJzm0NdfPK2Qbrz/OBsSRr4R7dBQmg+ylsfXROq4sjbHN1mcRIcEWBZ8JSly8X5JvQIgbfB5n658KIozryMkP/6SxrcZkkcPdzuSIG3+fy8C0i7e2+TBiVbr5vmphwev6AcrpqOFSh/n2bx1hLgyctyyFZi91YDv6yHlAzqOzL42TPlOh/Ys+WFlwUPcfK8XIjIXl9sEtoQGveqV/3jhwXe6IdaeYiO0X8/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
