//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;

namespace odec.CP.Server.Model.Store.Migrations {
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class _201604252249457_BlobStoreInitial {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        internal _201604252249457_BlobStoreInitial() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("odec.CP.Server.Model.Store.Migrations.201604252249457_BlobStoreInitial", typeof(_201604252249457_BlobStoreInitial).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to dbo.
        /// </summary>
        public static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to  H4sIAAAAAAAEAO09227cyJXvC+w/NPppN3DUkhwDE0NKIMszHiMjj2PZk7wJVHdZIoZNdki2IWeRL9uH/aT9hRRZJOt2Tl14a7aHMGCoWVXnnDq3up1T9f//+38Xf37aRosvJM3CJL5cnp2cLhckXiebMH64XO7zz7//bvnnP/3nf1x8v9k+LX6p6z0v6tGWcXa5fMzz3cvVKls/km2QnWzDdZpkyef8ZJ1sV8EmWZ2fnv5xdXa2IhTEksJaLC4+7OM83JLyB/15ncRrssv3QXSTbEiUVd9pyW0JdfEu2JJsF6zJ5ZJWWJ/ckpTSfFLWPrnNk5ScUBg5ecqzk1dRcr9cXEVhQIm7JdHn5SKI4yQPckr6y08Zuc3TJH643dEPQfTx647Qep+DKCNVl17y6q69Oz0verfiDWtQ632WJ1tPgGfPK3at1OatmL5s2EkZ+j1lfP616HXJ1MvldZCThyT9ulyoyF5eR2lREeJ53ar549kCr/SsURyqX8W/Z4vr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
